include: all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    included_file_warning: ignore

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    included_file_warning: false
    avoid_types_on_closure_parameters: false
    prefer_double_quotes: false
    public_member_api_docs: false
    prefer_expression_function_bodies: false
    prefer_final_parameters: false
